test if FFmpeg is correctly installed

diff --git a/vrecord b/vrecord
--- a/vrecord
+++ b/vrecord
@@ -3,6 +3,13 @@
 # vrecord
 # Open-source software for capturing a video signal and turning it into a digital file.
 
+if ffmpeg -version 2>&1 | grep "Library not loaded" >/dev/null; then
+    echo "Please wait while reinstalling 'FFmpeg'..."
+    brew reinstall ffmpeg \
+        && echo "OK: 'FFmpeg' reinstalled." \
+        || { echo "Error: 'FFmpeg' not installed correctly. Exiting." ; exit 1 ; }
+fi
+
 config_file="$HOME/.$(basename "${0}").conf"
 if [[ $(dirname $(which "${0}")) = "/usr/local/bin" ]] ; then
     version=$(TMP=$(brew info vrecord | grep -Eo "/vrecord/.* \(") ; echo ${TMP:9:(${#TMP}-11)})
