adjust functions shared with gtkdialog for compatibility

diff --git a/vrecord b/vrecord
--- a/vrecord
+++ b/vrecord
@@ -265,17 +265,17 @@ GTKDIALOG_FUNCTIONS=$(cat << 'GTKDIALOG_FUNCTION_DOC'
 _check_ffmpeg_install(){
     echo "Using ffmpeg at ${FFMPEG_BIN}"
     echo
-    if [[ ! -f "${FFMPEG_BIN}" ]] ; then
+    if [ ! -f "${FFMPEG_BIN}" ] ; then
         echo "${FFMPEG_BIN} is not found. Please install ffmpegdecklink via:"
         echo "    brew install amiaopensource/amiaos/ffmpegdecklink"
         echo "Or install a version of ffmpeg that is compiled with decklink support if you wish to use that input."
         echo
     fi
-    if [[ ! -f "${FFPLAY_BIN}" ]] ; then
+    if [ ! -f "${FFPLAY_BIN}" ] ; then
         echo "${FFPLAY_BIN} is not found."
         echo
     fi
-    if [[ ! -f "${FFPROBE_BIN}" ]] ; then
+    if [ ! -f "${FFPROBE_BIN}" ] ; then
         echo "${FFPROBE_BIN} is not found."
         echo
     fi
@@ -283,14 +283,14 @@ _check_ffmpeg_install(){
     FFMPEG_V="$("${FFMPEG_BIN}" -version 2>&1)"
     echo "FFmpeg configuration: ${FFMPEG_V}"
     echo
-    if [[ "$(echo "${FFMPEG_V}" | grep "Library not loaded" >/dev/null)" ]] ; then
+    if [ "$(echo "${FFMPEG_V}" | grep "Library not loaded" >/dev/null)" ] ; then
         echo "Please reinstall 'ffmpegdecklink':"
         echo "    brew reinstall amiaopensource/amiaos/ffmpegdecklink"
         echo "Or install a version of ffmpeg that is compiled with decklink support if you wish to use that input."
         echo "Exiting."
         exit 1
     fi
-    if [[ -z "$("${FFMPEG_BIN}" -nostdin -v 0 -sources decklink)" ]] ; then
+    if [ -z "$("${FFMPEG_BIN}" -nostdin -v 0 -sources decklink)" ] ; then
         echo "vrecord is set to use a decklink input but ${FFMPEG_BIN} does not appear to support decklink inputs."
         echo "Please review installation and troubleshooting information for vrecord or install ffmpegdecklink."
         exit 1
@@ -312,34 +312,29 @@ _update_config_file(){
 }
 
 _validate_form(){
-    VALIDATION_ERRORS=""
-    VALIDATION_WARNINGS=""
-    if [[ "${INVERT_PHASE}" = "true" ]] ; then
-        VALIDATION_WARNINGS+="WARNING: Option to invert phase of second audio channel has been selected.\n"
+    if [ "${INVERT_PHASE}" = "true" ] ; then
+        echo "WARNING: Option to invert phase of second audio channel has been selected.\n"
     fi
-    if [[ "${VIDEO_CODEC_CHOICE}" = "FFV1 version 3" ]] && [[ "${CONTAINER_CHOICE}" = "MXF" ]] ; then
-        VALIDATION_ERRORS+="ERROR: Incompatible video codecs and CONTAINERs have been selected.\n"
-    elif [[ "${AUDIO_CODEC_CHOICE}" = "24-bit FLAC" ]] && [[ "${CONTAINER_CHOICE}" = "QuickTime" ]] ; then
-        VALIDATION_ERRORS+="ERROR: Incompatible audio codecs and CONTAINERs have been selected.\n"
+    if [ "${VIDEO_CODEC_CHOICE}" = "FFV1 version 3" ] && [ "${CONTAINER_CHOICE}" = "MXF" ] ; then
+        echo "ERROR: Incompatible video codecs and containers have been selected.\n"
+    elif [ "${AUDIO_CODEC_CHOICE}" = "24-bit FLAC" ] && [ "${CONTAINER_CHOICE}" = "QuickTime" ] ; then
+        echo "ERROR: Incompatible audio codecs and containers have been selected.\n"
     fi
     # validate duration
-    if [[ -n "${DURATION}" ]] ; then
-        if ! [[ "${DURATION}" =~ ^$|^[0-9]+$|^[0-9]+\.[0-9]*$|^\.[0-9]+$ ]] ; then
-            VALIDATION_ERRORS+="ERROR: Illegal value for recording time. Input must only be numbers.\n"
-        elif (( $(bc <<< "${DURATION} == 0") )) ; then
-            VALIDATION_ERRORS+="ERROR: A recording duration of zero is invalid.\n"
+    if [ -n "${DURATION}" ] ; then
+        if ! [ "$(echo "${DURATION} > 0" | bc)" = "1" ] ; then
+            echo "ERROR: Illegal value for recording time. The duration must be a positive number.\n"
         fi
     fi
-    echo "${VALIDATION_ERRORS}${VALIDATION_WARNINGS}"
 }
 
 _get_output_filename(){
     # Get user suffix preference of default per video codec
-    if [[ -n "${USER_SUFFIX}" ]] ; then
+    if [ -n "${USER_SUFFIX}" ] ; then
         SUFFIX="${USER_SUFFIX}"
-    elif [[ "${NO_SUFFIX}" = 'true' ]] ; then
+    elif [ "${NO_SUFFIX}" = 'true' ] ; then
         SUFFIX=""
-    elif [[ "${DEVICE_INPUT_CHOICE}" = "0" ]] ; then
+    elif [ "${DEVICE_INPUT_CHOICE}" = "0" ] ; then
         case "${VIDEO_CODEC_CHOICE}" in 
             "FFV1 version 3")   SUFFIX="_ffv1" ;;
             "JPEG2000")         SUFFIX="_j2k" ;;
@@ -351,7 +346,7 @@ _get_output_filename(){
     fi
 
     # Get extension by container choice
-    if [[ "${DEVICE_INPUT_CHOICE}" = "0" ]] ; then
+    if [ "${DEVICE_INPUT_CHOICE}" = "0" ] ; then
         case "${CONTAINER_CHOICE}" in 
             "Matroska")             EXTENSION="mkv" ;;
             "QuickTime")            EXTENSION="mov" ;;
@@ -359,7 +354,7 @@ _get_output_filename(){
             "MXF")                  EXTENSION="mxf" ;;
             "MP4")                  EXTENSION="mp4" ;;
         esac
-    elif [[ "${DEVICE_INPUT_CHOICE}" = "2" ]] ; then
+    elif [ "${DEVICE_INPUT_CHOICE}" = "2" ] ; then
         case "${AUDIO_MODE_CODEC_CHOICE}" in
             "24-bit PCM")           EXTENSION="wav" ;;
             "24-bit FLAC")          EXTENSION="flac" ;;
